# Generated by Django 4.2.3 on 2023-07-12 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_pets_allowed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='house',
            old_name='price',
            new_name='price_per_month',
        ),
    ]
